server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "loans_qa.yml"
      - "loans_prod.yml"
  profiles:
    active:
      - "qa"

build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "rajarikam - Developer"
    email: "{cipher}c7ea77ad955ed7c8e0cce58c3d30db6deb93f6e3aee7023fc7dd5d74ad57b025bcaf867e0fcad625301a9a8dca4e5ecd"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934