spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related hook APIs "
  contactDetails:
    name: "rajarikam - Product Owner"
    email: "{cipher}c7ea77ad955ed7c8e0cce58c3d30db6deb93f6e3aee7023fc7dd5d74ad57b025bcaf867e0fcad625301a9a8dca4e5ecd"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956